<First_Page>:
    FitImage:
        source:'content/banner.jpg'
    MDRaisedButton:
        text: "Регистрация"
        md_bg_color: "red"
        pos_hint:{"center_x": 0.9, "center_y": 0.95}
        on_press:root.swap_on_reg()
    MDRaisedButton:
        text: "Вход"
        md_bg_color: "red"
        pos_hint:{"center_x": 0.78, "center_y": 0.95}
        on_press:root.swap_on_sign_in()
<RegisterScreen>:
    FitImage:
        source:'content/banner.jpg'
<Sign_In>:
    FitImage:
        source:'content/banner.jpg'
<Main_Project>:
    FitImage:
        source:'content/banner.jpg'
<MainPage>:
    FitImage:
        source:'content/banner.jpg'
<Notifications>:
    FitImage:
        source:'content/banner.jpg'